export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const FETCH_MORE_MOVIES = 'FETCH_MORE_MOVIES';
export const SET_TO_LOCALSTORAGE = 'SET_TO_LOCALSTORAGE';
export const CHANGE_FILTER = 'CHANGE_FILTER';
/*  ???
*/
export const SET_FROM_DATABASE = 'SET_FROM_DATABASE';
